project:
  application: vas-adapter-api
  name: vas-adapter-api
  chineseName: VAS基地适配层工程
  version:  ADAPTER_JD_V3R3D0320
  unpackTime: 2019/5/21
  PIC: wjggwm
  versionControlNo: 1.0
  versionControlPath:
  framework: SpringBoot

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    display-name: vas-adapter-api
    basedir: /tomcat
    accesslog:
      enabled: true
      buffered: true
      directory: ./logs
      file-date-format: _yyyy-MM-dd
      pattern: '%h %t "%r" %s %b %D %I "%{X-Forwarded-For}i" "%{User-Agent}i" "%{Referer}i" "%{X-Real-IP}i"'
      prefix: ${project.name}_accesslog
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
  # 上下文路径
  servlet:
    context-path: /vas-adapter-api
    display-name: vas-adapter-api

spring:
  profiles:
    #各个环境配置文件，需要修改  开发：dev， 测试：test，生产：prod
    active: dev
  application:
    name: vas-adapter-api
  task:
    pool:
      corePoolSize: 20
      maxPoolSize: 400
      keepAliveSeconds: 30000
      queueCapacity: 200
  dubbo:
    application:
    #注册在注册中心的名称，唯一标识，请勿重复
      id: zookeeper
      name: zookeeper
    #注册中心地址，zookeeper集群，启动输出可以看见链接了多个
    registry:
      address: zookeeper://127.0.0.1:2181
    #暴露服务方式
    protocol:
      id: dubbo
      #默认名称，勿修改
      name: dubbo
      #暴露服务端口 （默认是20880，修改端口，不同的服务提供者端口不能重复）
#      port: 20882
    #调用dubbo组建扫描的项目路径
    scan: com.test.service
    provider:
      validation: true
      timeout: 50000
      retries: 1
      loadbalance: leastactive
      #版本号分组信息
      group: zj
      version: 1.0
    consumer:
      check: false
      timeout: 30000
      retries: 1
      loadbalance: leastactive
      validation: true
      #版本号分组信息
      group: zj
      version: 1.0

logging:
  config: classpath:log/log4j2-${spring.profiles.active}.xml

#dubbo:
#  application:
#    id: ilss-consumer
#    name: ilss-consumer
#  registry:
#    protocol: zookeeper
#    address: 127.0.0.1:2181
#    id: registry-1
#  protocol:
#    name: dubbo
#    port: 20889
#  consumer:
#    version: 1.0

#调用第三方http接口配置
http:
  #超时时间，单位毫秒
  timeOut: 8000
  #最大连接数
  maxTotal: 400
  #单个路由最大连接数
  defaultMaxPerRoute: 200
  # 线程池配置
  thread-pool:
    core-pool-size: 50
    max-pool-size: 1000
    queue-capacity: 10000
    keep-alive-seconds: 300

#依赖系统的地址
dependency:
  #Ord地址
  yst-ord-api-url: http://127.0.0.1:8080/yst-ord-api
#系统参数配置（运营不关心的配置）
systemparameters:
  project:
    name: 'NVAS'
